name: CodeXPool
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  CodeXPool:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/CodeXPool
    resources:
      - path: Sources/CodeXPool/Resources
        excludes:
          - proxyd-prebuilt-archives
          - proxyd-prebuilt
      - path: Sources/CodeXPool/Resources/proxyd-prebuilt-archives
        type: folder
      - path: Sources/CodeXPool/Resources/proxyd-prebuilt
        type: folder
    settings:
      base:
        PRODUCT_NAME: CodeXPool
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleName: CodeXPool
        INFOPLIST_KEY_CFBundleDisplayName: CodeXPool
        INFOPLIST_KEY_LSMinimumSystemVersion: "14.0"
        INFOPLIST_KEY_LSUIElement: YES
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 12
        MARKETING_VERSION: 1.0.11
        DEVELOPMENT_TEAM: KLU8GF65GP
        PRODUCT_BUNDLE_IDENTIFIER: com.alick.copool
  CodeXPoolTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Tests/CodeXPoolTests
    dependencies:
      - target: CodeXPool
schemes:
  CodeXPool:
    build:
      targets:
        CodeXPool: all
        CodeXPoolTests: [test]
    test:
      targets:
        - CodeXPoolTests
